### ISSUE TITLE
The rules of war are wrong

### ISSUE THREAD

**Issue by isidore** [gigasquid/wonderland-clojure-katas#129]
In the game, if you have a tie, you don't resolve based on suit.

You deal three more cards from each hand and then 1 more that fights the war again. All cards go to the winner. If there is another tie, 3 more cards and fight again.

The main issue with the current rules is whomever receives the Ace of Hearts wins the game, as they can never lose the game as they can never run out of cards (nothing evers beats the ace of hearts)

**Comment by gigasquid** [comment]
Good point! PRs on this are most welcome 😸 ❤️ ♠️ ♦️ ♣️
