### ISSUE TITLE
Rules for tie in round (card-war-game)

### ISSUE THREAD

**Issue by LucianaMarques** [gigasquid/wonderland-clojure-katas#135]
Hello,

I just wanted to check if I should take in consideration the suits in consideration when there is a tie considering the ranks.

Both the [war games rules](https://en.wikipedia.org/wiki/War_%28card_game%29) and the [example scenario](https://github.com/LucianaMarques/wonderland-clojure-katas/blob/d1ad2515de5a9eae2619e4aefef7197fc79fa3f7/card-game-war/sample_scenario.md) state that we should not consider the suits. However, there are [some tests](https://github.com/gigasquid/wonderland-clojure-katas/blob/master/card-game-war/test/card_game_war/game_test.clj) that expect that the round results should consider the suits. 

If we should not take the suits into account, I believe some of the tests need to be rewritten (I can submit a PR with changes).

Thanks!

**Comment by gigasquid** [comment]
Thanks for bringing this up. The example scenario was added from this issue https://github.com/gigasquid/wonderland-clojure-katas/issues/129 - but the tests were never adjusted to match it. If you are up for submitting a PR with the changes it would be great :)

**Comment by LucianaMarques** [comment]
I will submit it then! Thanks

**Comment by LucianaMarques** [comment]
Opened PR #136 !

**Comment by aruscher** [comment]
Hello,
i have further questions refering to the rules of the game:

1. What should happend if one player runs out of cards during a "war"?
